#!/bin/bash
cd "${0%/*}" || exit 1

echo "Cleaning current directory..."

rm -f output/non-regression.json
rm -f output/*.vtu
rm -f output/*.png
rm -f *.msh
rm -f log.*
rm -f *.png

echo "Done. Output and temporary files deleted."
