#!/bin/bash

echo "Cleaning current directory..."

rm -f output/*.vtu
rm -f output/*.png
rm -f output/non-regression.json
rm -f *.msh *.vtk *.vtu log.z3st

echo "Done. Output and temporary files deleted."
