#!/bin/bash
cd "${0%/*}" || exit 1

(cd thermal_conductivity_magni && bash ./Allclean)
(cd thermal_conductivity_GPR && bash ./Allclean)

rm -f thermal_conductivity_comparison.png temperature_profile_comparison.png
