#!/bin/bash
cd "${0%/*}" || exit 1

echo "Training the conductivity network..."
python3 train_knet.py

gmsh mesh.geo -2 > log_mesh.md
python3 -m z3st > log_z3st.md

python3 non-regression.py
python3 ../../../../utils/plot_convergence.py log_z3st.md
