#!/usr/bin/env python3
# --.. ..- .-.. .-.. --- --.. ..- .-.. .-.. --- --.. ..- .-.. .-.. ---
# Z3ST: An open-source FEniCSx framework for thermo-mechanical analysis
# Author: Giovanni Zullo
# Version: 0.2.0 (2026)
# --.. ..- .-.. .-.. --- --.. ..- .-.. .-.. --- --.. ..- .-.. .-.. ---

# --.. ..- .-.. .-.. --- Z3ST utility module --.. ..- .-.. .-.. ---
"""
Z3ST utility: utils_extract_vtu.py
----------------------------------

Provides functions for extracting physical fields from VTU files
generated by Z3ST simulations. Supports temperature, stress, and
displacement extraction, as well as automatic detection of field
names and coordinate handling.

Typical usage:
--------------
    from utils_extract_vtu import extract_temperature, extract_stress, extract_displacement, list_fields

    x, y, z, T = extract_temperature("output/fields.vtu")
    x, y, z, sigma_xx = extract_stress("output/fields.vtu", component="xx")
    x, y, z, U = extract_displacement("output/fields.vtu")

Author: Giovanni Zullo
Project: Z3ST
Date: 11/10/2025
"""

# --.. ..- .-.. .-.. --- imports --.. ..- .-.. .-.. ---
import os

import numpy as np
import pandas as pd
import pyvista as pv


# --.. ..- .-.. .-.. --- helpers --.. ..- .-.. .-.. ---
def _detect_field(grid, field_name, info=False):
    """Find field in VTU file, searching in point and cell data."""
    fname = field_name
    if fname in grid.point_data:
        if info: print(f"[INFO] Found field in point_data: '{field_name}'")
        return "point", field_name
    elif fname in grid.cell_data:
        if info: print(f"[INFO] Found field in cell_data: '{field_name}'")
        return "cell", field_name
    raise KeyError(f"<{field_name}> field not found in VTU file.")


def _detect_temp_field(grid):
    """Find temperature field name in VTU file"""
    for name in ("Temperature", "temperature", "T", "temp"):
        if name in grid.point_data:
            print(f"[INFO] Found temperature field in point_data: '{name}'")
            return "point", name
        elif name in grid.cell_data:
            print(f"[INFO] Found temperature field in cell_data: '{name}'")
            return "cell", name
    raise KeyError("Temperature field not found in VTU file.")


def _detect_displacement(grid):
    """Find displacement field name in VTU file"""
    for name in ("Displacement", "displacement", "U", "u"):
        if name in grid.point_data:
            print(f"[INFO] Found displacement field in point_data: '{name}'")
            return "point", name
        elif name in grid.cell_data:
            print(f"[INFO] Found displacement field in cell_data: '{name}'")
            return "cell", name
    raise KeyError("Displacement field not found in VTU file.")


def _detect_sigma(grid, prefer="points"):
    """
    Detect the stress field in the VTU file.
    Prefer 'Stress (points)' if available, otherwise fallback to cell data.
    """
    if prefer == "points":
        for name in grid.point_data.keys():
            if "stress" in name.lower():
                print(f"[INFO] Found stress field in point_data: '{name}'")
                return "point", name

    elif prefer == "cells":
        for name in grid.cell_data.keys():
            if "stress" in name.lower():
                print(f"[INFO] Found stress field in cell_data: '{name}'")
                return "cell", name

    else:
        raise ValueError(f"Invalid prefer value '{prefer}'. Choose 'points' or 'cells'.")

    print("\n[ERROR] No stress field found in VTU file.")
    print("Available point_data:", list(grid.point_data.keys()))
    print("Available cell_data:", list(grid.cell_data.keys()))
    raise KeyError("No stress field found containing 'Stress'.")


def _data_coords(grid, location, field_name):
    """Retrieve data array and coordinates based on location (point or cell)"""
    if location == "point":
        data = grid.point_data[field_name]
        coords = grid.points
    elif location == "cell":
        data = grid.cell_data[field_name]
        coords = grid.cell_centers().points
    else:
        raise ValueError(f"Invalid location '{location}'. Must be 'point' or 'cell'.")
    return data, coords


# --.. ..- .-.. .-.. --- field listing --.. ..- .-.. .-.. ---
def list_fields(vtu_path):
    """
    List all point_data and cell_data fields in a VTU file.
    Check also the mesh grid.
    """
    if not os.path.exists(vtu_path):
        raise FileNotFoundError(f"VTU file not found: {vtu_path}")

    grid = pv.read(vtu_path)
    print(f"[INFO] Reading VTU file: {vtu_path}")

    print("\n[AVAILABLE FIELDS]")
    print("  Point data:")
    if grid.point_data:
        for i, name in enumerate(grid.point_data.keys(), 1):
            arr = grid.point_data[name]
            print(f"    {i:2d}) {name:<30} shape={arr.shape}")
    else:
        print("    None")

    print("\n  Cell data:")
    if grid.cell_data:
        for i, name in enumerate(grid.cell_data.keys(), 1):
            arr = grid.cell_data[name]
            print(f"    {i:2d}) {name:<30} shape={arr.shape}")
    else:
        print("    None")

    grid = pv.read(vtu_path)
    xmin, xmax, ymin, ymax, zmin, zmax = grid.bounds
    print(f"\n[INFO] Grid bounds:")
    print(f"\tx ∈ [{xmin:.4e}, {xmax:.4e}]")
    print(f"\ty ∈ [{ymin:.4e}, {ymax:.4e}]")
    print(f"\tz ∈ [{zmin:.4e}, {zmax:.4e}]")


# --.. ..- .-.. .-.. --- extractors --.. ..- .-.. .-.. ---
def extract_field(vtu_path, field_name, return_coords=True, info=False):
    """
    Extract a field (scalar or vector) and coordinates from a VTU file.

    Parameters
    ----------
    vtu_path : str
        Path to the .vtu file.
    field_name : str
        Name of the field to extract (e.g. "temperature", "heat_flux").
    return_coords : bool, optional
        If True, returns x, y, z arrays together with the field.

    Returns
    -------
    field : np.ndarray
        Numpy array of field values (Nx1 for scalars, Nx3 for vectors).
    (x, y, z) : np.ndarray, np.ndarray, np.ndarray (optional)
        Coordinates of each point (or cell center if data is in cell_data).
    """
    if not os.path.exists(vtu_path):
        raise FileNotFoundError(f"VTU file not found: {vtu_path}")

    grid = pv.read(vtu_path)

    loc_t, field_t = _detect_field(grid, field_name, info=info)
    data, coords = _data_coords(grid, loc_t, field_t)

    if return_coords:
        x, y, z = coords[:, 0], coords[:, 1], coords[:, 2]
        return x, y, z, data
    else:
        return data


def extract_temperature(vtu_path, return_coords=True):
    """
    Extract temperature field and coordinates from VTU.

    Parameters
    ----------
    vtu_path : str
        Path to the .vtu file.
    return_coords : bool, optional
        If True, returns x, y, z arrays together with temperature.

    Returns
    -------
    temperature : np.ndarray
        Numpy array of temperature values.
    (x, y, z) : np.ndarray, np.ndarray, np.ndarray (optional)
        Coordinates of each data point or cell center.
    """
    if not os.path.exists(vtu_path):
        raise FileNotFoundError(f"VTU file not found: {vtu_path}")

    grid = pv.read(vtu_path)

    loc_t, field_t = _detect_temp_field(grid)
    data, coords = _data_coords(grid, loc_t, field_t)

    if return_coords:
        x, y, z = coords[:, 0], coords[:, 1], coords[:, 2]
        return x, y, z, data
    else:
        return data


def extract_displacement(vtu_path, return_coords=True):
    """
    Extract displacement field and coordinates from VTU.

    Parameters
    ----------
    vtu_path : str
        Path to the .vtu file.
    return_coords : bool, optional
        If True, returns x, y, z arrays together with displacement.

    Returns
    -------
    displacement : np.ndarray
        Numpy array of displacement values.
    (x, y, z) : np.ndarray, np.ndarray, np.ndarray (optional)
        Coordinates of each data point or cell center.
    """
    if not os.path.exists(vtu_path):
        raise FileNotFoundError(f"VTU file not found: {vtu_path}")

    grid = pv.read(vtu_path)

    loc, field = _detect_displacement(grid)
    data, coords = _data_coords(grid, loc, field)

    if return_coords:
        x, y, z = coords[:, 0], coords[:, 1], coords[:, 2]
        return x, y, z, data
    else:
        return data


def extract_stress(vtu_path, component="xx", return_coords=True, prefer="cells"):
    """
    Extract stress tensor from VTU (by default σ_xx).

    Parameters
    ----------
    vtu_path : str
        Path to the .vtu file.
    component : str, optional
        Stress tensor component to extract ('xx', 'yy', 'zz', 'xy', 'xz', 'yz').
    return_coords : bool, optional
        If True, returns x, y, z arrays together with stress component.
    prefer : str, optional
        "points" or "cells" (default: "points").

    Returns
    -------
    stress_comp : np.ndarray
        Array of the selected stress component.
    (x, y, z) : np.ndarray, np.ndarray, np.ndarray (optional)
        Coordinates corresponding to stress values.
    """
    if not os.path.exists(vtu_path):
        raise FileNotFoundError(f"VTU file not found: {vtu_path}")

    grid = pv.read(vtu_path)

    loc_s, field_name = _detect_sigma(grid, prefer=prefer)
    data, coords = _data_coords(grid, loc_s, field_name)

    data = np.asarray(data)
    if data.ndim == 2 and data.shape[1] == 9:
        stress_tensors = data.reshape(-1, 3, 3)
    else:
        raise ValueError(f"Unexpected stress data shape: {data.shape}")

    x, y, z = coords[:, 0], coords[:, 1], coords[:, 2]
    comp_map = {"xx": (0, 0), "yy": (1, 1), "zz": (2, 2), "xy": (0, 1), "xz": (0, 2), "yz": (1, 2)}
    if component == "all":
        comps = {
            "xx": stress_tensors[:, 0, 0],
            "yy": stress_tensors[:, 1, 1],
            "zz": stress_tensors[:, 2, 2],
            "xy": stress_tensors[:, 0, 1],
            "xz": stress_tensors[:, 0, 2],
            "yz": stress_tensors[:, 1, 2],
        }
        return x, y, z, comps if return_coords else comps

    if component not in comp_map:
        raise ValueError(f"Invalid component '{component}'. Choose among {list(comp_map.keys())}.")

    i, j = comp_map[component]
    stress_comp = stress_tensors[:, i, j]

    return x, y, z, stress_comp if return_coords else stress_comp


def extract_principal_stresses(
    vtu_path,
    return_coords=True,
    prefer="points",
    average=None,
    n_bins=100,
    decimals=3,
    bandwidth=0.0005,
):
    """
    Extract principal stresses (σ₁, σ₂, σ₃) from a VTU file by diagonalizing
    the stress tensor at each point or cell, with optional radial averaging.

    Parameters
    ----------
    vtu_path : str
        Path to the .vtu file.
    return_coords : bool, optional
        If True, returns (x, y, z) coordinates.
    prefer : str, optional
        Prefer 'points' or 'cells' when both exist in VTU.
    average : str or None, optional
        Radial averaging method: 'bins', 'weighted', 'kernel', 'round', or None.
    n_bins : int, optional
        Number of bins for 'bins' or 'weighted' averaging.
    decimals : int, optional
        Round precision for 'round' averaging.
    bandwidth : float, optional
        Kernel bandwidth for 'kernel' averaging.

    Returns
    -------
    sigma1, sigma2, sigma3 : np.ndarray
        Arrays of the three principal stresses (ordered σ₁ ≥ σ₂ ≥ σ₃),
        optionally radially averaged.
    (x, y, z) : np.ndarray, np.ndarray, np.ndarray (optional)
        Coordinates of each point or cell center.
    """
    x, y, z, comps = extract_stress(vtu_path, component="all", return_coords=True, prefer=prefer)

    s_xx, s_yy, s_zz = comps["xx"], comps["yy"], comps["zz"]
    s_xy, s_xz, s_yz = comps["xy"], comps["xz"], comps["yz"]

    stress_tensors = np.stack(
        [
            np.stack([s_xx, s_xy, s_xz], axis=1),
            np.stack([s_xy, s_yy, s_yz], axis=1),
            np.stack([s_xz, s_yz, s_zz], axis=1),
        ],
        axis=1,
    )  # shape (N,3,3)

    eigvals = np.linalg.eigvalsh(stress_tensors)
    sigma1, sigma2, sigma3 = eigvals[:, 2], eigvals[:, 1], eigvals[:, 0]

    if average:
        from z3st.utils.utils_plot import (
            radial_average_kernel,
            radial_average_round,
            radial_average_uniform_bins,
            radial_average_weighted,
        )

        print(f"[INFO] Applying radial averaging ({average}) on principal stresses...")

        if average == "bins":
            r_avg, sigma1 = radial_average_uniform_bins(x, y, z, sigma1, n_bins=n_bins)
            _, sigma2 = radial_average_uniform_bins(x, y, z, sigma2, n_bins=n_bins)
            _, sigma3 = radial_average_uniform_bins(x, y, z, sigma3, n_bins=n_bins)
        elif average == "weighted":
            r_avg, sigma1 = radial_average_weighted(x, y, z, sigma1, n_bins=n_bins)
            _, sigma2 = radial_average_weighted(x, y, z, sigma2, n_bins=n_bins)
            _, sigma3 = radial_average_weighted(x, y, z, sigma3, n_bins=n_bins)
        elif average == "kernel":
            r_avg, sigma1 = radial_average_kernel(x, y, z, sigma1, bandwidth=bandwidth)
            _, sigma2 = radial_average_kernel(x, y, z, sigma2, bandwidth=bandwidth)
            _, sigma3 = radial_average_kernel(x, y, z, sigma3, bandwidth=bandwidth)
        elif average == "round":
            r_avg, sigma1 = radial_average_round(x, y, z, "sigma1", sigma1, decimals=decimals)
            _, sigma2 = radial_average_round(x, y, z, "sigma2", sigma2, decimals=decimals)
            _, sigma3 = radial_average_round(x, y, z, "sigma3", sigma3, decimals=decimals)
        else:
            raise ValueError(f"Unknown averaging method '{average}'.")

        if return_coords:
            return r_avg, np.zeros_like(r_avg), np.zeros_like(r_avg), sigma1, sigma2, sigma3
        else:
            return sigma1, sigma2, sigma3

    if return_coords:
        return x, y, z, sigma1, sigma2, sigma3
    else:
        return sigma1, sigma2, sigma3


def extract_cylindrical_field(
    filename="output/fields.vtu",
    z_fixed=0.0,
    tol=1e-3,
    case_dir=".",
    field_hint="Strain",
    data_source="cell",
    average=True,
    decimals=6,
    save_results=False,
):
    # Load file
    if not os.path.exists(filename):
        raise FileNotFoundError(f"[ERROR] File not found: {filename}")
    grid = pv.read(filename)

    # Detect field name
    actual_field_name = None
    data_obj = grid.cell_data if data_source == "cell" else grid.point_data

    for key in data_obj.keys():
        if field_hint.lower() in key.lower():
            actual_field_name = key
            break

    if actual_field_name is None:
        raise KeyError(
            f"No field found containing '{field_hint}' in {data_source}_data of {filename}"
        )

    print(f"[INFO] Extracting '{actual_field_name}' from {data_source}_data")

    # Data extraction
    if data_source == "cell":
        raw_values = grid.cell_data[actual_field_name]
        field_values = raw_values.reshape((-1, 3, 3))
        coords = grid.cell_centers().points
    else:
        raw_values = grid.point_data[actual_field_name]
        field_values = raw_values.reshape((-1, 3, 3))
        coords = grid.points

    # Select slice
    mask = np.abs(coords[:, 2] - z_fixed) < tol
    if np.sum(mask) == 0:
        raise ValueError(f"No data found at z = {z_fixed:.4e} ± {tol:.1e}")

    x, y = coords[mask, 0], coords[mask, 1]

    fxx, fyy, fzz, fxy = (
        field_values[mask, 0, 0],
        field_values[mask, 1, 1],
        field_values[mask, 2, 2],
        field_values[mask, 0, 1],
    )

    # Convert to cylindrical
    r = np.sqrt(x**2 + y**2)
    theta = np.arctan2(y, x)
    c, s = np.cos(theta), np.sin(theta)

    frr = fxx * c**2 + fyy * s**2 + 2 * fxy * s * c
    ftt = fxx * s**2 + fyy * c**2 - 2 * fxy * s * c
    fzz = fzz

    import pandas as pd

    df = pd.DataFrame({"r": r, "frr": frr, "ftt": ftt, "fzz": fzz}).sort_values("r")

    if average:
        df["r"] = df["r"].round(decimals)
        df = df.groupby("r")[["frr", "ftt", "fzz"]].mean().reset_index()

    if save_results:
        out_dir = os.path.join(case_dir, "output")
        os.makedirs(out_dir, exist_ok=True)
        csv_path = os.path.join(out_dir, f"{field_hint.lower()}_cylindrical_z{z_fixed:.2f}.csv")
        df.to_csv(csv_path, index=False)

    return (
        df["r"].to_numpy(),
        df["frr"].to_numpy(),
        df["ftt"].to_numpy(),
        df["fzz"].to_numpy(),
    )


def average_section(x, y, z, field, y0, z0, tol=1e-3, decimals=5, label="field"):
    """Extract and average field along x at fixed y,z plane."""
    mask = (np.abs(y - y0) < tol) & (np.abs(z - z0) < tol)
    if not np.any(mask):
        raise RuntimeError(f"[ERROR] No points found for {label} (tol={tol})")
    df = (
        pd.DataFrame({"x": x[mask].round(decimals), label: field[mask]})
        .groupby("x", as_index=False)
        .mean()
    )
    return df["x"].to_numpy(), df[label].to_numpy()


def average_section_radial(x, y, z, field, z_target, tol=1e-3, decimals=5):
    """Average a scalar field over constant-z plane along radius r = sqrt(x² + y²)."""
    r = np.sqrt(x**2 + y**2)
    mask = np.abs(z - z_target) < tol
    if not np.any(mask):
        raise RuntimeError(f"No points found near z={z_target:.3f} ± {tol:.1e}")
    df = pd.DataFrame({"r": r[mask].round(decimals), "f": field[mask]})
    df = df.groupby("r", as_index=False).mean()
    return df["r"].to_numpy(), df["f"].to_numpy()
