#!/bin/bash
set -e
cd "${0%/*}" || exit 1

for case in \
  uniform_Pu_porosity_magni \
  uniform_Pu_porosity_GPR \
  olander_Pu_burnup_magni \
  olander_Pu_burnup_GPR
do
  (cd "$case" && bash ./Allrun)
done

python3 compare_cases.py
