#!/bin/bash
cd "${0%/*}" || exit 1  # Run from this directory

echo "Executing z3st.py..."

gmsh mesh.geo -3 > log_mesh.md

python3 -m z3st > log_z3st.md

python3 non-regression.py

python3 ../../../utils/plot_convergence.py
