#!/bin/bash

echo "Executing z3st.py..."

gmsh mesh.geo -3 > log_mesh.md

# conda run -n z3st python3 -m z3st

# conda run -n z3st python3 non-regression.py

python3 -m z3st > log_z3st.md

python3 non-regression.py