#!/bin/bash
cd "${0%/*}" || exit 1

echo "Cleaning current directory..."

rm -f output/non-regression.json
rm -f output/fields.*
rm -f output/*.pvd
rm -f output/*.png
rm -f output/*.csv
rm -f *.msh
rm -f log_*.md
rm -rf __pycache__

echo "Done. Output and temporary files deleted (gold record preserved)."
