#!/bin/bash
cd "${0%/*}" || exit 1

echo "Cleaning current directory..."

rm -f output/non-regression.json
rm -f output/fields.vtu
rm -f output/fields_*.vtu
rm -f output/*.pvd
rm -f output/*.png
rm -f output/*.csv
rm -f *.msh
rm -f log_*.md

echo "Done. Output and temporary files deleted (gold record preserved)."
