#!/bin/bash
cd "${0%/*}" || exit 1

echo "Cleaning current directory..."

rm -f output/non-regression.json output/case_summary.json
rm -f output/*.vtu output/*.pvd output/*.xdmf output/*.h5 output/*.png output/*.csv
rm -f *.msh
rm -f *.png
rm -f log_*.md

echo "Done. All output and temporary files cleaned."
