#!/bin/bash
cd "${0%/*}" || exit 1  # Run from this directory

echo "Cleaning current directory..."

rm -f output/non-regression.json output/case_summary.json
rm -f output/*.vtu output/*.pvd output/*.xdmf output/*.h5 output/*.png output/*.csv
rm -f log_*.md

echo "Done. Output and temporary files deleted."
