#!/bin/bash
cd "${0%/*}" || exit 1  # Run from this directory

echo "Cleaning current directory..."

rm -rf output
rm -f *.msh
rm -f *.png
rm -f *.txt

echo "Done. Output and temporary files deleted."
