#!/bin/bash
cd "${0%/*}" || exit 1  # Run from this directory

echo "Cleaning current directory..."

rm -f output/non-regression.json
rm -f output/fields.vtu
rm -f output/*.png
rm -f output/*.csv
rm -f *.msh
rm -f *.png
rm -f *.txt

echo "Done. Output and temporary files deleted."
