#!/bin/bash
cd "${0%/*}" || exit 1  # Run from this directory

echo "Executing z3st.py..."

gmsh mesh.geo -3

python3 -m z3st > log.txt

python3 example.py

python3 ../../utils/plot_convergence.py log.txt
