#!/bin/bash
cd "${0%/*}" || exit 1  # Run from this directory

echo "Cleaning current directory..."

rm -rf output __pycache__
rm -f *.msh
rm -f log_*.md
rm -r *.png

echo "Done. Output and temporary files deleted."
