#!/bin/bash
cd "${0%/*}" || exit 1

echo "Executing z3st.py..."

gmsh mesh.geo -2 -o mesh.msh

conda run -n z3st python3 -m z3st > log.z3st

conda run -n z3st python3 non-regression.py

conda run -n z3st python3 ../../utils/plot_convergence.py
