# --.. ..- .-.. .-.. --- --.. ..- .-.. .-.. --- --.. ..- .-.. .-.. ---
# Z3ST: An open-source FEniCSx framework for thermo-mechanical analysis
# Author: Giovanni Zullo
# Version: 0.1.0 (2025)
# --.. ..- .-.. .-.. --- --.. ..- .-.. .-.. --- --.. ..- .-.. .-.. ---

from pathlib import Path

import dolfinx
from mpi4py import MPI

from z3st.core.diagnostic import log


class GmshMeshReader:
    """Load a mesh generated by Gmsh (.msh) into a dolfinx.Mesh."""

    def __init__(self, comm: MPI.Comm = MPI.COMM_WORLD):
        self.comm = comm
        self.rank = comm.rank

    def load(self, mesh_path: Path, gdim: int = 3):
        """Read mesh data from file and return dolfinx mesh + tags."""
        mesh_path = Path(mesh_path)
        if not mesh_path.exists():
            raise FileNotFoundError(f"Mesh file not found: {mesh_path}")

        log.info(f"Loading mesh from {mesh_path.name}")

        try:
            # FEniCSx ≥ 0.10.0 – returns an object with attributes mesh, cell_tags, facet_tags
            mesh_data = dolfinx.io.gmsh.read_from_msh(
                str(mesh_path), MPI.COMM_WORLD, rank=self.rank, gdim=gdim
            )
            mesh, cell_tags, facet_tags = (
                mesh_data.mesh,
                mesh_data.cell_tags,
                mesh_data.facet_tags,
            )
        except AttributeError:
            # Backward compatibility for FEniCSx ≤ 0.9.x
            from dolfinx import io

            mesh, cell_tags, facet_tags = io.gmshio.read_from_msh(
                str(mesh_path),
                comm=self.comm,
                rank=self.rank,
                gdim=gdim,
            )

        log.info("Mesh successfully loaded from Gmsh file.")
        return mesh, cell_tags, facet_tags
