# --.. ..- .-.. .-.. --- --.. ..- .-.. .-.. --- --.. ..- .-.. .-.. ---
# Z3ST: An open-source FEniCSx framework for thermo-mechanical analysis
# Author: Giovanni Zullo
# Version: 0.2.0 (2026)
# --.. ..- .-.. .-.. --- --.. ..- .-.. .-.. --- --.. ..- .-.. .-.. ---

from pathlib import Path

import dolfinx
from mpi4py import MPI

from z3st.core.diagnostic import log


class GmshMeshReader:
    """Load a mesh generated by Gmsh (.msh) into a dolfinx.Mesh."""

    def __init__(self, comm: MPI.Comm = MPI.COMM_WORLD):
        self.comm = comm
        self.rank = comm.rank

    def load(self, mesh_path: Path, gdim: int = 3):
        """Read mesh data from file and return dolfinx mesh + tags."""
        mesh_path = Path(mesh_path)
        if not mesh_path.exists():
            raise FileNotFoundError(f"Mesh file not found: {mesh_path}")

        log.info(f"Loading mesh from {mesh_path.name}")

        try:
            # FEniCSx ≥ 0.10.0 – returns an object with attributes mesh, cell_tags, facet_tags
            mesh_data = dolfinx.io.gmsh.read_from_msh(
                str(mesh_path),
                MPI.COMM_WORLD,
                rank=self.rank,
            )
            mesh, cell_tags, facet_tags = (
                mesh_data.mesh,
                mesh_data.cell_tags,
                mesh_data.facet_tags,
            )
        except AttributeError:
            # Backward compatibility for FEniCSx ≤ 0.9.x
            from dolfinx import io

            mesh, cell_tags, facet_tags = io.gmshio.read_from_msh(
                str(mesh_path),
                comm=self.comm,
                rank=self.rank,
                gdim=gdim,
            )

        log.info("Mesh successfully loaded from Gmsh file.")
        return mesh, cell_tags, facet_tags


class XdmfMeshReader:
    """Load a mesh generated by XDMF into a dolfinx.Mesh."""
    
    def __init__(self, comm: MPI.Comm = MPI.COMM_WORLD):
        self.comm = comm
        self.rank = comm.rank
        
    def load(self, mesh_path: Path):
        mesh_path = Path(mesh_path)
        if not mesh_path.exists():
            raise FileNotFoundError(f"Mesh file not found: {mesh_path}")
            
        log.info(f"Loading mesh from {mesh_path.name}")
        
        with dolfinx.io.XDMFFile(self.comm, mesh_path, "r") as xdmf:
            try:
                mesh = xdmf.read_mesh(name="Grid")
            except RuntimeError:
                mesh = xdmf.read_mesh(name="mesh")
            
            mesh.topology.create_connectivity(mesh.topology.dim - 1, mesh.topology.dim)

            try:
                cell_tags = xdmf.read_meshtags(mesh, name="CellTags")
            except RuntimeError:
                log.warning("Could not find 'CellTags' in XDMF. Trying default...")
                try:
                    cell_tags = xdmf.read_meshtags(mesh, name="Grid")
                except RuntimeError:
                    log.warning("Could not find cell tags.")
                    cell_tags = None
            
            try:
                facet_tags = xdmf.read_meshtags(mesh, name="FacetTags")
            except RuntimeError:
                log.warning("Could not find 'FacetTags' in XDMF")
                facet_tags = None
                

            
        return mesh, cell_tags, facet_tags

